#!/bin/sh
#
# Minimal regression test suite.

if [ ! -d tests/outputs ]; then
	mkdir tests/outputs
fi

dhcpd-pools -f J -c $top_srcdir/tests/confs/same-twice \
		 -l $top_srcdir/tests/leases/same-twice |
		sed '/"version":"/d; /"conf_file_.*":/d; /"lease_file_.*":/d' \
		>| tests/outputs/same-twice-json
diff -u $top_srcdir/tests/expected/same-twice-json tests/outputs/same-twice-json
exit $?
